schema_version: 1

context:
  name: azure-mgmt-hdinsight
  version: 9.0.0b3

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/azure-mgmt-hdinsight-${{ version }}.tar.gz
  sha256: 72549e08ff3eed3d6e23835e73ece1cc32bdf340bdf8919e78916c352c200f64

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python

requirements:
  host:
    - setuptools
    - python ${{ python_min }}.*
    - pip
  run:
    - python >=${{ python_min }}
    - azure-common >=1.1
    - azure-mgmt-core >=1.3.2
    - isodate >=0.6.1
    - typing-extensions >=4.6.0

tests:
  - python:
      imports:
        - azure.mgmt.hdinsight
        - azure.mgmt.hdinsight.aio
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Microsoft Azure HDInsight Management Client Library for Python
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/Azure/azure-sdk-for-python

extra:
  recipe-maintainers:
    - janjagusch
